# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  name: "kinoshita-local"

#variables:
#- name: LD_LIBRARY_PATH
#  value: "${LD_LIBRARY_PATH}:~/_work/_tool/Python/3.11.13/x64/lib"

strategy:
  matrix:
#    Python38:
#      python.version: '3.8'
#    Python39:
#      python.version: '3.9'
#    Python310:
#      python.version: '3.10'
    Python311:
      python.version: '3.11'

steps:

- script: |
    echo "##vso[task.setvariable variable=LD_LIBRARY_PATH;]:/home/azureuser/agent/_work/_tool/Python/3.11.13/x64/lib"
    echo "LD_LIBRARY_PATH is: $LD_LIBRARY_PATH"
  displayName: 'Set LD_LIBRARY_PATH'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    source ~/.venv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source ~/.venv/bin/activate
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
